web:
 image: komplizierte/docker-nginx-magento:latest
 dns: 8.8.8.8
 ports:
  - "80:80"
 extra_hosts:
  - "mysql:192.168.1.34"
 volumes:
  - .:/var/www/magento
 environment:
  BASE_URL: http://m.local/
